name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: deploy
      url: 'https://web.math.ucsb.edu/~siam'
    steps:
      - name: Setup SSH Keys and known_hosts
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SIAM_PRIVATE_KEY }}
          name: siam
          known_hosts: ${{ secrets.SIAM_KNOWN_HOSTS }}
          config: |
            Host siam
              HostName web.math.ucsb.edu
              User siam
              IdentityFile ~/.ssh/siam

      - uses: actions/checkout@master

      - name: SCP the build to the server
        run: |
          ssh siam rm -r "~/public_html/"
          scp -r ./src siam:~/public_html
