name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the site
        run: |
          echo "There is currently no build setup"
          mkdir dist
          touch dist/somefile
          echo "hi" > dist/somefile
      - uses: actions/upload-artifact@master
        with:
          name: bundle
          path: ./dist/
       
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: deploy
      url: 'https://web.math.ucsb.edu/~siam'
    steps:
      - name: Setup SSH Keys and known_hosts
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SIAM_PRIVATE_KEY }}
          name: siam
          known_hosts: ${{ secrets.SIAM_KNOWN_HOSTS }}
          config: |
            Host siam
              HostName web.math.ucsb.edu
              User siam
              IdentityFile ~/.ssh/siam
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: bundle
          path: ./dist/

      - name: SCP the build to the server
        run: |
          scp -r ./dist siam:~/
